// <auto-generated />
using CarRental.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CarRental.Infrastructure.Persistence.Migrations;

[DbContext(typeof(CarRentalDbContext))]
[Migration("20260911120000_AddActiveRentalExclusionConstraint")]
partial class AddActiveRentalExclusionConstraint;
